export const ICONS = {
  mosque: 'fas fa-mosque',
  home: 'fas fa-home',
  contract: 'fas fa-file-contract',
  email: 'fas fa-envelope-open-text',
  pieChart: 'fas fa-chart-pie',
  chevronRight: 'fas fa-chevron-right',
  chevronLeft: 'fas fa-chevron-left',
  under_construction: 'fas fa-paint-roller',
  ready_for_shopping: 'fas fa-book-reader',
  location: 'fas fa-map',
  under_license: 'fas fa-file',
  fa_vials: 'fas fa-vials',
  newspaper: 'far fa-newspaper',
  question: 'fas fa-question',
  fa_heartbeat: 'fas fa-heartbeat',
  chalkboard: 'fas fa-chalkboard-teacher',
  fa_columns: 'fas fa-columns',
};
